### ISSUE TITLE
Replace values in triggers and other objects

### ISSUE THREAD

**Issue by daveschnee** [SQLPlayer/azure.datafactory.tools#16]
Hi Kamil

Sorry, this isn't a bug but I didn't know where to post a question

When you attach a pipeline that has parameters to a trigger, these parameter values are contained in the definition file itself - See attached as an example. 

My question is: How do I replace these values in the environment based configuration files considering there could be x number of parameters and multiple pipelines attached to the same trigger with completely different parameters

Thanks a lot

[TR_Daily_7PM_AWST.txt](https://github.com/SQLPlayer/azure.datafactory.tools/files/4726679/TR_Daily_7PM_AWST.txt)

**Comment by NowinskiK** [comment]
Hi @daveschnee again. That is a great question.  
Although I'm aware of that inconvenience, it is not easy to conquer it due to the current approach of providing a path to field in JSON files which disallow determining location by key rather than index.
This need to be addressed in another way and will come soon with the feature enabling the users replacing values from DevOps pipeline (both from normal and secret variables).
As a temporary solution, you can add another task in your pipeline to replace these values (tokens) in JSON file.

**Comment by daveschnee** [comment]
Hi Kamil

Thanks for the update. I have noticed that you can do this using the native ARM template parameter override in the Microsoft documentation

https://docs.microsoft.com/en-us/azure/data-factory/continuous-integration-deployment#custom-parameter-syntax

I was hoping to use your solution to provide a json string for the array of pipelines and parameters to override the pipelines array in the json definition file by using your config file. Is that a potential option?

On 4 Jun 2020, at 19:58, Kamil Nowinski <notifications@github.com> wrote:

﻿

Hi @daveschnee<https://github.com/daveschnee> again. That is a great question.
Although I'm aware of that inconvenience, it is not easy to conquer it due to the current approach of providing a path to field in JSON files which disallow determining location by key rather than index.
This need to be addressed in another way and will come soon with the feature enabling the users replacing values from DevOps pipeline (both from normal and secret variables).
As a temporary solution, you can add another task in your pipeline to replace these values (tokens) in JSON file.

**Comment by NowinskiK** [comment]
Definitely. That sounds very reasonable. Thanks for the example.
