### ISSUE TITLE
Support for managedVirtualNetwork and managedPrivateEndpoint

### ISSUE THREAD

**Issue by card78** [SQLPlayer/azure.datafactory.tools#95]
Thanks for this wonderful tool.

Are there any plans to support managedVirtualNetwork and managedPrivateEndpoint?

**Comment by NowinskiK** [comment]
Hey, thanks.
They are still in preview, so probably when go out as GA.

**Comment by ragzzy** [comment]
@NowinskiK Thank you so very much for helping the ADF community with this tool.  I support this feature request, and looking forward to it.

**Comment by Golovac** [comment]
Hi @NowinskiK, thank you for the great tool. 
I'm also looking forward to this enhancement. Do you have any updates on it?

**Comment by NowinskiK** [comment]
Guys, thanks for your patience. 
This feature will be released today as a preview (prerelease) in PowerShell Gallery.

Option **Drop not in source** is NOT supported yet for Managed Private Endpoints.

**Comment by NowinskiK** [comment]
https://www.powershellgallery.com/packages/azure.datafactory.tools/0.70.0-preview

**Comment by Golovac** [comment]
Hi @NowinskiK, 
Thanks again for the great tool! 
I'm using the preview version in order to deploy the Data Factory with the private end points and I'm getting an error when I try to update some of the properties for the private end point before deploying it.
Here is the error:
Get-AdfObjectByPattern : ADFT0015: Type [managedVirtualNetwork\default\managedPrivateEndpoint] is not supported.
At C:\Users\golovachevan\Documents\WindowsPowerShell\Modules\azure.datafactory.tools\0.70.0\private\Update-PropertiesFromFile.ps1:64 char:19
+ ...    $objArr = Get-AdfObjectByPattern -adf $adf -name $name -type $type
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-AdfObjectByPattern
Here is the value from the config file for the private end point:
    "cra-devdata-dbserver-PEP":[
        {
            "name": "$.properties.typeProperties.ssisProperties.catalogInfo.catalogServerEndpoint",
            "value": "$Env:SQLSERVERNAME.database.windows.net",
            "action": "update"
        }
    ]

I would really appreciate your help. Thanks.

**Comment by NowinskiK** [comment]
Hi @Golovac.
Could you show me your config file?

**Comment by Golovac** [comment]
Hi @NowinskiK,
Thank you for your prompt response.
I have changed the file extension from json to txt in order to get it attached here.
[publish_config.txt](https://github.com/SQLPlayer/azure.datafactory.tools/files/6919715/publish_config.txt)

**Comment by NowinskiK** [comment]
Will be rolled out in the nearest release.
